import { expect, test } from '@playwright/test'
import { advance, startGame, state } from './game-fixture.js'

test('fires and renders one front projectile through the real keyboard control', async ({ page }) => {
  await startGame(page)
  const canvas = page.locator('canvas')
  const before = await canvas.screenshot()
  await page.keyboard.down('Space')
  await advance(page, 100)
  await page.keyboard.up('Space')
  const fired = await state(page)
  expect(fired.projectiles).toHaveLength(1)
  expect(fired.projectiles[0]).toMatchObject({ weapon: 'frontFire', heading: 0, damage: 20, speed: 400 })
  expect(fired.projectiles[0].x).toBeCloseTo(236)
  expect(fired.effects.some(({ kind }) => kind === 'fire')).toBe(true)
  expect((await canvas.screenshot()).equals(before)).toBe(false)
})

test('fires parallel broadsides and respects independent held-fire cooldowns', async ({ page }) => {
  await startGame(page)
  for (const key of ['Space', 'q', 'e']) await page.keyboard.down(key)
  await advance(page, 350)
  let fired = await state(page)
  expect(fired.projectiles.filter(({ weapon }) => weapon === 'frontFire')).toHaveLength(1)
  for (const weapon of ['leftFire', 'rightFire']) {
    const side = fired.projectiles.filter((projectile) => projectile.weapon === weapon)
    expect(side).toHaveLength(3)
    expect(side.map(({ x }) => x)).toEqual([134, 150, 166])
    expect(new Set(side.map(({ heading }) => heading)).size).toBe(1)
    expect(side[0].heading).toBeCloseTo(weapon === 'leftFire' ? -Math.PI / 2 : Math.PI / 2)
  }
  await advance(page, 1000 / 60)
  fired = await state(page)
  expect(fired.projectiles.filter(({ weapon }) => weapon === 'frontFire')).toHaveLength(2)
  expect(fired.cooldowns).toEqual({ frontFire: 700, leftFire: 1000, rightFire: 1000 })
  await advance(page, 650)
  expect((await state(page)).cooldowns.leftFire).toBeCloseTo(2000)
  expect((await state(page)).cooldowns.rightFire).toBeCloseTo(2000)
  for (const key of ['Space', 'q', 'e']) await page.keyboard.up(key)
})

test('removes front shots at the island and renders one impact', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('Space')
  await advance(page, 100)
  await page.keyboard.up('Space')
  await advance(page, 450)
  const hit = await state(page)
  expect(hit.projectiles).toHaveLength(0)
  expect(hit.effects).toEqual([expect.objectContaining({ kind: 'impact', x: 396, y: 350 })])
  expect(hit.score).toBe(0)
  await advance(page, 200)
  expect((await state(page)).effects).toHaveLength(0)
})

test('expires unobstructed front shots at the configured reach', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('d')
  await advance(page, 500)
  await page.keyboard.up('d')
  await page.keyboard.down('w')
  await advance(page, 1400)
  await page.keyboard.up('w')
  await page.keyboard.down('a')
  await advance(page, 500)
  await page.keyboard.up('a')
  await page.keyboard.down('Space')
  await advance(page, 100)
  await page.keyboard.up('Space')
  await advance(page, 1300)
  expect((await state(page)).projectiles).toHaveLength(1)
  await advance(page, 100)
  expect((await state(page)).projectiles).toHaveLength(0)
  expect((await state(page)).effects).toHaveLength(0)
})

test('freezes projectiles and cooldowns on pause without replaying held fire', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('Space')
  await advance(page, 50)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const paused = await state(page)
  await advance(page, 10000)
  expect(await state(page)).toEqual(paused)
  await page.getByRole('button', { name: 'Resume' }).click()
  await page.keyboard.down('Space')
  await advance(page, 350)
  expect((await state(page)).cooldowns).toEqual(paused.cooldowns)
  await page.keyboard.up('Space')
  await page.keyboard.down('Space')
  await advance(page, 1000 / 60)
  await page.keyboard.up('Space')
  expect((await state(page)).cooldowns.frontFire).toBeCloseTo(750)
})

test('moves and fires with simultaneous touch contacts and releases on cancellation', async ({ page }) => {
  await startGame(page)
  const controls = ['Forward', 'Front Fire', 'Left Fire', 'Right Fire']
  const points = await Promise.all(controls.map(async (name, id) => {
    const bounds = (await page.getByRole('button', { name, exact: true }).boundingBox())!
    return { id, x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2 }
  }))
  const protocol = await page.context().newCDPSession(page)
  await protocol.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: points })
  await advance(page, 100)
  const fired = await state(page)
  expect(fired.player.x).toBeCloseTo(168)
  expect(fired.projectiles).toHaveLength(7)
  await protocol.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  await advance(page, 400)
  const released = await state(page)
  expect(released.player).toEqual(fired.player)
  expect(released.cooldowns).toEqual(fired.cooldowns)
  await protocol.detach()
})

test('stops weapons at completion and clears them on restart', async ({ page }) => {
  await startGame(page)
  await advance(page, 119950)
  await page.keyboard.down('q')
  await advance(page, 50)
  await expect(page.getByRole('heading', { name: 'Voyage complete' })).toBeVisible()
  const completed = await state(page)
  await advance(page, 5000)
  expect(await state(page)).toEqual(completed)
  await page.keyboard.up('q')
  await page.getByRole('button', { name: 'Play Again', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.__game?.getState().status)).toBe('running')
  expect((await state(page)).projectiles).toHaveLength(0)
  expect((await state(page)).effects).toHaveLength(0)
  expect((await state(page)).cooldowns).toEqual({ frontFire: 0, leftFire: 0, rightFire: 0 })
})
