import { expect, test } from '@playwright/test'
import { advance, startGame, state } from './game-fixture.js'

test('spawns both types at safe scheduled positions and reproduces a seed', async ({ page }) => {
  await startGame(page)
  await advance(page, 2999)
  expect((await state(page)).spawnCount).toBe(0)
  await advance(page, 1)
  const first = await state(page)
  expect(first.enemies[0].kind).toBe('chaser')
  for (const enemy of first.enemies) {
    expect(enemy.x).toBeGreaterThanOrEqual(40)
    expect(enemy.x).toBeLessThanOrEqual(960)
    expect(enemy.y).toBeGreaterThanOrEqual(40)
    expect(enemy.y).toBeLessThanOrEqual(660)
    expect(Math.hypot(enemy.x - 500, enemy.y - 350)).toBeGreaterThanOrEqual(140)
    expect(Math.hypot(enemy.x - first.player.x, enemy.y - first.player.y)).toBeGreaterThanOrEqual(250)
  }
  await advance(page, 3000)
  const second = await state(page)
  expect(second.spawnCount).toBe(2)
  expect(second.enemies.some(({ kind }) => kind === 'shooter')).toBe(true)
  await startGame(page)
  await advance(page, 6000)
  expect(await state(page)).toEqual(second)
})

test('uses the saved spawn interval for a new match', async ({ page }) => {
  await page.goto('/?e2e=1&seed=42')
  await page.getByRole('button', { name: 'Options', exact: true }).click()
  await page.getByLabel('Enemy spawn time').fill('1')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Main Menu', exact: true }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(window.__game))).toBe(true)
  await advance(page, 999)
  expect((await state(page)).spawnCount).toBe(0)
  await advance(page, 1)
  expect((await state(page)).spawnCount).toBe(1)
  await advance(page, 1000)
  expect((await state(page)).spawnCount).toBe(2)
  expect((await state(page)).config.enemySpawnInterval).toBe(1)
})

test('makes the Chaser approach, impact once and disappear without scoring', async ({ page }) => {
  await startGame(page, 'chaser-impact')
  await advance(page, 1000 / 60)
  expect((await state(page)).enemies[0].x).toBeLessThan(235)
  await advance(page, 100)
  const hit = await state(page)
  expect(hit.enemies).toHaveLength(0)
  expect(hit.player.hp).toBe(75)
  expect(hit.score).toBe(0)
  await expect(page.getByText('Health: 75', { exact: true })).toBeVisible()
  expect(hit.effects.some(({ kind }) => kind === 'destruction')).toBe(true)
  await advance(page, 1000)
  expect((await state(page)).player.hp).toBe(75)
})

test('makes the Shooter respect its first cooldown and apply one projectile hit', async ({ page }) => {
  await startGame(page, 'shooter-attack')
  await advance(page, 1499)
  expect((await state(page)).projectiles).toHaveLength(0)
  await advance(page, 1)
  expect((await state(page)).projectiles[0]).toMatchObject({ team: 'enemy', damage: 10, speed: 250 })
  await advance(page, 300)
  expect((await state(page)).player.hp).toBe(90)
  expect((await state(page)).projectiles).toHaveLength(0)
  await expect(page.getByText('Health: 90', { exact: true })).toBeVisible()
  await advance(page, 500)
  expect((await state(page)).player.hp).toBe(90)
})

test('blocks enemy shots on the island', async ({ page }) => {
  await startGame(page, 'island-cover')
  await advance(page, 1700)
  expect((await state(page)).projectiles).toHaveLength(0)
  expect((await state(page)).player.hp).toBe(100)
  expect((await state(page)).effects.some(({ kind }) => kind === 'impact')).toBe(true)
})

test('freezes enemies, cooldowns and spawn scheduling during pause', async ({ page }) => {
  await startGame(page)
  await advance(page, 6000)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const paused = await state(page)
  await advance(page, 30000)
  expect(await state(page)).toEqual(paused)
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await advance(page, 100)
  expect((await state(page)).elapsedMs).toBeCloseTo(paused.elapsedMs + 100)
  expect((await state(page)).spawnCount).toBe(paused.spawnCount)
})
