import { expect, test } from '@playwright/test'
import { advance, startGame, state } from './game-fixture.js'

test('pauses on browser focus loss and requires explicit resume', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('w')
  await advance(page, 500)
  const protocol = await page.context().newCDPSession(page)
  await protocol.send('Emulation.setFocusEmulationEnabled', { enabled: false })
  const otherPage = await page.context().newPage()
  await otherPage.goto('about:blank')
  await otherPage.bringToFront()
  await expect(page.getByRole('dialog')).toBeVisible()
  const paused = await state(page)
  await advance(page, 10000)
  expect(await state(page)).toEqual(paused)
  await page.bringToFront()
  await protocol.send('Emulation.setFocusEmulationEnabled', { enabled: true })
  expect((await state(page)).status).toBe('paused')
  await page.getByRole('button', { name: 'Resume' }).click()
  await page.keyboard.down('w') // A still-held key emits a repeat, not a fresh press.
  await advance(page, 500)
  expect((await state(page)).player).toEqual(paused.player)
  await otherPage.close()
  await page.keyboard.up('w')
  await protocol.detach()
})

test('pauses and resumes without replaying held controls or time', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('w')
  await advance(page, 500)
  await page.keyboard.press('p')
  await expect(page.getByRole('dialog')).toBeVisible()
  const paused = await state(page)
  await advance(page, 10000)
  expect(await state(page)).toEqual(paused)
  await page.getByRole('button', { name: 'Resume' }).click()
  await page.keyboard.down('w')
  await advance(page, 500)
  expect((await state(page)).player).toEqual(paused.player)
  expect((await state(page)).elapsedMs).toBeCloseTo(1000)
  await page.keyboard.up('w')
})

test('returns to the menu with clean input and starts a new session', async ({ page }) => {
  await startGame(page)
  await page.keyboard.down('w')
  await advance(page, 300)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Main Menu' }).click()
  await expect(page.locator('canvas')).toHaveCount(0)
  expect(await page.evaluate(() => window.__game)).toBeUndefined()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => page.evaluate(() => Boolean(window.__game))).toBe(true)
  await advance(page, 500)
  expect((await state(page)).player.x).toBe(150)
  await page.keyboard.up('w')
})

test('completes at active time and restarts with fresh state', async ({ page }) => {
  await startGame(page)
  await advance(page, 120000)
  await expect(page.getByRole('heading', { name: 'Voyage complete' })).toBeVisible()
  const completed = await state(page)
  expect(completed.elapsedMs).toBe(120000)
  await advance(page, 5000)
  expect(await state(page)).toEqual(completed)
  await page.getByRole('button', { name: 'Play Again' }).click()
  await expect.poll(() => page.evaluate(() => window.__game?.getState().status)).toBe('running')
  expect((await state(page)).elapsedMs).toBe(0)
  expect((await state(page)).player.x).toBe(150)
})
